# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false

reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!uv.lock"
    - "!**/*.generated.*"
    - "!**/*.onnx"
  path_instructions:
    - path: "qwen3_embed/common/**"
      instructions: "Review for ONNX Runtime performance: session options, memory management, batch processing efficiency."
    - path: "qwen3_embed/text/**"
      instructions: "Review for embedding correctness: pooling strategies, normalization, tokenizer handling."

chat:
  auto_reply: true
